# Generated by Django 3.2.5 on 2021-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('project_name', models.CharField(max_length=250)),
                ('project_sort_desc', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('project_link', models.CharField(max_length=150)),
                ('project_image', models.ImageField(blank=True, null=True, unique=True, upload_to='')),
            ],
        ),
    ]
