# Generated by Django 3.2.5 on 2021-07-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_downlod_able',
            field=models.BooleanField(default=False),
        ),
    ]
