# Generated by Django 3.2.5 on 2021-07-26 03:02

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_downlod_able'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.modify_project_files),
        ),
    ]
