# Generated by Django 3.2.5 on 2021-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='email_for',
            field=models.CharField(choices=[('new_contact', 'New contact'), ('new_post', 'New Post'), ('new_subscription', 'New subscription')], max_length=255),
        ),
    ]
