# Generated by Django 3.2.5 on 2021-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_queue', '0002_alter_emailqueue_email_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='ref_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
