# Generated by Django 3.2.5 on 2021-08-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_queue', '0003_emailqueue_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
