# Generated by Django 3.2.5 on 2021-07-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
