# Generated by Django 3.2.5 on 2021-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_response',
            field=models.CharField(choices=[('1', 'Responsed'), ('0', 'Not Responsed')], default='0', max_length=255),
        ),
    ]
