# Generated by Django 3.2.5 on 2021-07-21 23:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(blank=True, null=True, unique=True, upload_to=blog.models.modify_upload_file_name)),
                ('blog_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
