# Generated by Django 3.2.5 on 2021-07-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_sort_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_sl_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
