# Generated by Django 3.2.5 on 2021-08-01 12:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.modify_upload_file_name),
        ),
    ]
