# Generated by Django 3.2.5 on 2021-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish_status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='0', max_length=255),
        ),
    ]
